In [2]:
import pandas
df = pandas.read_csv("sample.csv", delimiter='\t')
df

,配達区分,お届け先 郵便番号,お届け先 電話番号,お届け先 住所1,お届け先 住所2,お届け先 住所3,お届け先 氏名,希望月,希望日,希望時間,...,品名1,品名2,クール便,代金引換額,受付日の年,受付日の月,受付日の日,お届け予定月,お届け予定日,品名欄右
0,1,761-8057,087-869-7377,香川県高松市,田村町,968-1,日本システム開発株式会社,2,1,1,...,パソコン本体 X 1,キーボード、マウス X 1,NaN,150000.0,19,1,27,2,1,伝票№ 19010010
1,0,761-8057,087-869-7377,香川県高松市,田村町,968-1,開発 二郎,2,2,2,...,パソコン本体 X 2,キーボード、マウス X 2,NaN,NaN,19,1,28,2,2,伝票№ 19010011
2,0,761-8057,087-869-7377,香川県高松市,田村町,968-1,開発 三郎,2,3,3,...,パソコン本体 X 3,キーボード、マウス X 3,NaN,NaN,19,1,29,2,3,伝票№ 19010012

In [3]:
df.head(2)

,配達区分,お届け先 郵便番号,お届け先 電話番号,お届け先 住所1,お届け先 住所2,お届け先 住所3,お届け先 氏名,希望月,希望日,希望時間,...,品名1,品名2,クール便,代金引換額,受付日の年,受付日の月,受付日の日,お届け予定月,お届け予定日,品名欄右
0,1,761-8057,087-869-7377,香川県高松市,田村町,968-1,日本システム開発株式会社,2,1,1,...,パソコン本体 X 1,キーボード、マウス X 1,NaN,150000.0,19,1,27,2,1,伝票№ 19010010
1,0,761-8057,087-869-7377,香川県高松市,田村町,968-1,開発 二郎,2,2,2,...,パソコン本体 X 2,キーボード、マウス X 2,NaN,NaN,19,1,28,2,2,伝票№ 19010011

In [6]:
df[["配達区分", "品名1"]]

   配達区分         品名1
0     1  パソコン本体 X 1
1     0  パソコン本体 X 2
2     0  パソコン本体 X 3

In [7]:
df[df['受付日の日'] > 27]

,配達区分,お届け先 郵便番号,お届け先 電話番号,お届け先 住所1,お届け先 住所2,お届け先 住所3,お届け先 氏名,希望月,希望日,希望時間,...,品名1,品名2,クール便,代金引換額,受付日の年,受付日の月,受付日の日,お届け予定月,お届け予定日,品名欄右
1,0,761-8057,087-869-7377,香川県高松市,田村町,968-1,開発 二郎,2,2,2,...,パソコン本体 X 2,キーボード、マウス X 2,NaN,NaN,19,1,28,2,2,伝票№ 19010011
2,0,761-8057,087-869-7377,香川県高松市,田村町,968-1,開発 三郎,2,3,3,...,パソコン本体 X 3,キーボード、マウス X 3,NaN,NaN,19,1,29,2,3,伝票№ 19010012